### ISSUE TITLE
bug: View bug when loading posts on Firefox.

### ISSUE THREAD

**Issue by efyre** [transfem-org/Sharkey#100]
## 💡 Summary

Scrolling down a page and then loading new posts makes the view go back up.

## 🥰 Expected Behavior

Load post and not move, and allow the user to continue peacefully.

## 🤬 Actual Behavior

When scrolling down a profile (might be on timeline too, but I could not test),  when you arrive "at the end"
and posts needs to be loaded, instead of staying put the camera goes back up.
Only happens on Firefox, I tried to replicate without success in other browsers.

(Video attached showing the bug, and I am sorry the 10 first seconds are still)

https://github.com/transfem-org/Sharkey/assets/130368725/ed51c786-69d4-4f41-acc9-b52fd4da180e

## 📝 Steps to Reproduce

1. Open Firefox.
2. Go to a Sharkey instance.
3. Scroll down a profile.

## 📌 Environment

Firefox 118.0.2.

I managed to replicate the bug on two other devices, I don't know the version of the firefox of those devices though.
Issue also happend when in a private window, so it's not because of extensions.

### 💻 Frontend
* Model and OS of the device(s):
  Was tested on Windows 10 and Arch Linux
* Browser:
  Firefox 118.0.2.
* Server URL:
  https://transfem.social
* Sharkey:
  v2023.10.1

**Comment by Insert5StarName** [comment]
this has been fixed already and will be in the next update that releasing shortly

**Comment by efyre** [comment]
Oh. Welp sorry about that ^^"

**Comment by Insert5StarName** [comment]
> Oh. Welp sorry about that ^^"

no worries, better report it twice than have it not reported

**Comment by efyre** [comment]
Fair yeah
