### ISSUE TITLE
feat: show previous versions of edited notes

### ISSUE THREAD

**Issue by dakkar** [transfem-org/Sharkey#103]
## Summary

* an API endpoint, that works like `/notes/show` but returns all versions of the note
* a button or menu item on the web frontend, shown only for edited notes, that calls that endpoint and shows all the versions
    * probably in a "window" like "… / ⓘdetails" already does

**Comment by Mar0xy** [comment]
> a button or menu item on the web 

I would probably put the versions into the edited icon as a menu that shows up on the notes

**Comment by dakkar** [comment]
so would I, but didn't want to sound prescriptive 😅
