### ISSUE TITLE
MFM can overlap post info & overflow into replies

### ISSUE THREAD

**Issue by Freeplayg** [transfem-org/Sharkey#104]
## 💡 Summary

MFM can overlap post information, and overflow into the replies:
![image](https://github.com/transfem-org/Sharkey/assets/40742947/0851900a-7725-46f2-a235-9b72248f1874)

## 🥰 Expected Behavior
![image](https://github.com/transfem-org/Sharkey/assets/40742947/36fb4eb4-f711-47b8-b5ec-6363c607b88b)

## 📝 Steps to Reproduce

https://kitsunes.club/notes/9kvd8ksxx89hfmzv

### 💻 Frontend
* Model and OS of the device(s): Fedora 38, Gnome

* Browser: Firefox 118.0.2

* Server URL: kitsunes.club

* Misskey: 2023.10.2

**Comment by Insert5StarName** [comment]
thx for the report i will look into it, tho im arguably not the best at css

**Comment by Freeplayg** [comment]
You should be able to add a `position: relative; z-index: 1 or higher whatever gets it to not go under` to the containers that need it

You should also be able to add `overflow: hidden` to the entire post's container to not get it to flow into the replies
