### ISSUE TITLE
bug: "..." button is gone in note detail (mobile)

### ISSUE THREAD

**Issue by codingneko** [transfem-org/Sharkey#106]
Note detail context menu (... button) isn't showing up on mobile. I assume it's because it doesn't fit in the screen.

![Screenshot_2023-10-22-13-27-05-862_com android chrome](https://github.com/transfem-org/Sharkey/assets/11065075/36d7ff18-914c-41ac-a027-1c7f9c529900)

**Comment by Insert5StarName** [comment]
im unable to debug this as i currently have no phone i recommend checking the previous commit that was working with the button placement and playing around with it on your own fork then making a pr

**Comment by codingneko** [comment]
> im unable to debug this as i currently have no phone i recommend checking the previous commit that was working with the button placement and playing around with it on your own fork then making a pr

Will try tomorrow, I hope I can get the dev env to start cause last time I failed miserably xd

**Comment by codingneko** [comment]
Seems like this was an instance specific bug or got fixed in a recent commit. I cannot replicate this anymore so I'll close the issue :)
