### ISSUE TITLE
Followers-only posts show as private in timeline when boosted, even to followers

### ISSUE THREAD

**Issue by eeeyrie** [transfem-org/Sharkey#108]
## 💡 Summary

Followers-only posts show as private in timeline when boosted, even to followers

## 🥰 Expected Behavior

Followers-only posts should be visible to followers in timeline when boosted

## 🤬 Actual Behavior

Follower-only posts are still private to followers when boosted
![image](https://github.com/transfem-org/Sharkey/assets/77976308/21c3ab15-f4d8-4656-b45e-17a9f00e7030)
![image](https://github.com/transfem-org/Sharkey/assets/77976308/63fe2d5d-5e9a-48f7-a6e0-f434cd836733)
![image](https://github.com/transfem-org/Sharkey/assets/77976308/0ee2bb62-3179-4c02-9ad2-6d50216d2f89)

## 📝 Steps to Reproduce

1. Create a post with follower-only visibility
2. Boost that post
3. Try to view the boost from a following account

### 💻 Frontend
* Model and OS of the device(s): Thinkpad L380 Yoga, Arch Linux (rolling)
  
* Browser: Firefox 118.0.2
  
* Server URL: transfem.social
  
* Sharkey: 2023.10.2

**Comment by Mar0xy** [comment]
I am fully lost on what you actually mean when I make an post with follower-only visibility and then boost it and view it from an account that follows the person it shows up just normally.

![image](https://github.com/transfem-org/Sharkey/assets/8841466/e252f6b8-8811-43b4-a220-3c5cc65c9684)

**Comment by Mar0xy** [comment]
Might have found a possible cause will fix it in a bit
