### ISSUE TITLE
build error related to megalodon

### ISSUE THREAD

**Issue by tastytea** [transfem-org/Sharkey#111]
the issue was [already reported](https://github.com/transfem-org/Sharkey/issues/47#issuecomment-1743806725) but the solution was not shared.

## 💡 Summary

the build process errors when coming to `packages/megalodon`. i'm using the build instructions on [misskey-hub](https://misskey-hub.net/en/docs/install/manual.html) since i didn't find sharkey specific instructions.

## 🥰 Expected Behavior

build succeeds

## 🤬 Actual Behavior

excerpt of the errors:

```
packages/megalodon build: src/friendica.ts(3,29): error TS7016: Could not find a declaration file for module 'parse-link-header'. '/opt/misskey/sharkey/node_modules/.pnpm/parse-link-header@2.0.0/node_modules/parse-link-header/index.js' implicitly has an 'any' type.
packages/megalodon build:   Try `npm i --save-dev @types/parse-link-header` if it exists or add a new declaration (.d.ts) file containing `declare module 'parse-link-header';`
```

→ [full build log](https://github.com/transfem-org/Sharkey/files/13079522/build.log)

## 📝 Steps to Reproduce

1. check out fresh sharkey stable branch
2. `git submodule update --init`
3. `NODE_ENV=production pnpm install --frozen-lockfile`
4. `NODE_ENV=production pnpm run build`

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: manual
* Sharkey: stable branch
* Node: 20.6.1
* PostgreSQL: 15.4
* Redis: 7.2.1
* OS and Architecture: Gentoo Linux amd64

**Comment by Insert5StarName** [comment]
what branch are you on?

**Comment by Mar0xy** [comment]
Please use install without NODE_ENV

**Comment by tastytea** [comment]
thanks, that worked. i don't see how this would be obvious to someone who doesn't program with nodejs though.

**Comment by Mar0xy** [comment]
This issue will be gone after the rewrite of the Mastodon API as megalodon will be dropped out of the packages that are needed then.
