### ISSUE TITLE
Wrong stats in api/v1/instance

### ISSUE THREAD

**Issue by mkostera** [transfem-org/Sharkey#113]
## 💡 Summary

API in api/v1/instance shows fake numbers

## 🥰 Expected Behavior

Should be same like in nodeinfo/2.1.

## 🤬 Actual Behavior

https://nerdout.online/nodeinfo/2.1    4 users
https://nerdout.online/api/v1/instance    4171 users

Same bug was in Calckey, so I suppose Sharkey is clone of it, or copied wrong code.

**Comment by Insert5StarName** [comment]
the mastodon api is currently being rewritten without the Megalodon Module if this done this should be fixed

also we aren't a calckey clone or fork and we also don't use their code
