### ISSUE TITLE
feat: image description edits should federate

### ISSUE THREAD

**Issue by tastytea** [transfem-org/Sharkey#116]
## 💡 Summary

edits to image descriptions are not federated. they only show up locally.

## 📝 Steps to Reproduce

1. post a note with an image
2. edit the note
3. edit the image description
4. look at the note on another instance

### 💻 Frontend
* Model and OS of the device(s):
  Gentoo Linux
* Browser:
  Firefox 115.3.1
* Server URL:
  very.tastytea.de
* Sharkey:
  2023.10.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: manual
* Sharkey: 2023.10.2
* Node: 20.6.1
* PostgreSQL: 15.4
* Redis: 7.2.1
* OS and Architecture: Gentoo Linux amd64

**Comment by Mar0xy** [comment]
Currently the edit implementation is generally missing updating files due to the complexity added by the drive feature letting you update the alt text as well but it's planned to be added eventually down the line.

**Comment by Mar0xy** [comment]
This has now been fixed with the commit `9383e3a`
