### ISSUE TITLE
Including files tab contains posts that do not include files

### ISSUE THREAD

**Issue by codingneko** [transfem-org/Sharkey#118]
## 💡 Summary
The "Including files" tab in user notes contains posts that do NOT have a file because they reply to posts that do contain a file.

## 🥰 Expected Behavior

Only replies / posts that contain files should be shown, the post being replied to should not be a factor.

## 🤬 Actual Behavior

The Including Files tab is filled with replies to posts that contain a file, but that have no files, making the posts that actully have a file much harder to find.

## 📝 Steps to Reproduce

Access a profile from a user that has posted images or videos, and that has replied to posts with images or videos (most profiles fit this criteria), click on the "Notes" tab, and click on the "Including files" tab. Look at the posts that show up. Most of them do not have any files, they just reply to posts that do.

## 📌 Environment

2023.10.3.beta1

### 💻 Frontend
  Currently on this, but affects all devices probably.
* Model and OS of the device(s):
  Windows 11 Developer Preview
* Browser:
  Chrome 118.0.5993.118
* Server URL:
  https://misskey.codingneko.com
* Sharkey:
  2023.10.3.beta1

### 🛰 Backend (for server admin)
Self-hosted on bare-metal server running Ubuntu 22.04.3 LTS x86_64

* Installation Method or Hosting Service: 
* Dockerised with modified docker-compose.yml script (build .) and de-rounded (see https://misskey.codingneko.com/Sharkey at develop 4e07839)
* OS and Architecture: Ubuntu 22.04.3 LTS x86_64

**Comment by codingneko** [comment]
Acutally I'm not sure this is related to the original post having an image anymore... these do not have a file at all... I think the filter might just straight up not be working at all
![image](https://github.com/transfem-org/Sharkey/assets/11065075/912fe5ba-9100-4640-859f-afe4bf15e82b)

**Comment by dakkar** [comment]
I think I fixed this, see https://github.com/transfem-org/Sharkey/pull/122
