### ISSUE TITLE
bug: emoji autocomplete and control panel emoji search should be case insensitive

### ISSUE THREAD

**Issue by MoshiBar** [transfem-org/Sharkey#129]
### 💡 Summary

when typing a post, the emoji autocomplete menu that pops up is case sensitive when searching for emoji
the same issue happens for the emoji search in the control panel.

### 🥰 Expected Behavior

Emoji searches and autocomplete should be case insensitive. this is already the case for the emoji picker menu

### 🤬 Actual Behavior

see above

### 📝 Steps to Reproduce

N/A

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Arch Linux, GrapheneOS
* Browser: Firefox Flatpak, Happens on Mobile Firefox as well
* Server URL: ambrosia.moe
* Misskey: 13.x.x
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: baremetal
* Misskey: Sharkey commit 9a73e98
* Node: v19.9.0
* PostgreSQL: docker
* Redis: docker
* OS and Architecture: Debian 11
```

**Comment by Mar0xy** [comment]
This was fixed for the autocomplete but not the admin panel as the emoji search being case sensitive is very important to find bad emojis easily if they are in caps while other instances might have the same emoji name but different emoji in no caps.
