### ISSUE TITLE
bug: Relays Broken

### ISSUE THREAD

**Issue by moyitpro** [transfem-org/Sharkey#133]
### 💡 Summary

I noticed in the latest release that relays are no longer working. Messages from server 1 (sharkeytest1.tamaki-shimai.moe) does not appear on server 2 (sharkeytest2.tamaki-shimai.moe), which is connected to the relay that is locally accessible only, relaytest.tamaki-shimai.moe. It seems the Sharkey isn't pulling new posts from the relay in the latest dev release compared to the stable release (see expected behavior)

Note: A Relay allows ActivityPub servers that are joined to it to exchange all posts between the servers that are in the relay

### 🥰 Expected Behavior

Server 1 messages should appear on Server 2, which is joined by the same relay and vice versa.

Pic in the screenshot below, which is from the publicly accessible test server, sharkey.tamaki-shimai.moe running the stable release of Sharkey, it's receiving posts I don't follow from the relay connected at relay.sakurajima.moe
<img width="1527" alt="2023-11-02_19-51-40" src="https://github.com/transfem-org/Sharkey/assets/161183/e4344751-0018-4858-af6c-e087506930f4">

<img width="801" alt="2023-11-02_19-53-06" src="https://github.com/transfem-org/Sharkey/assets/161183/8351e800-4ae8-4d8f-8fe8-72144d6097cb">

### 🤬 Actual Behavior

I can reproduce this by creating two Sharkey servers in a local environment running on the latest Ubuntu 22.04.3 LTS release running on the dev branch. Messages made on server 1 isn't showing up on the federated timeline of server 2 and vice versa.

<img width="2484" alt="2023-11-02_19-45-49" src="https://github.com/transfem-org/Sharkey/assets/161183/1383bb08-ddb4-45eb-83ad-e56b6105902f">
<img width="2484" alt="2023-11-02_19-45-15" src="https://github.com/transfem-org/Sharkey/assets/161183/daec66d1-c373-4085-9e13-9128b52b4e3a">

<img width="2484" alt="2023-11-02_19-44-37" src="https://github.com/transfem-org/Sharkey/assets/161183/6708b6a6-3ec5-4145-85b6-427e0c82e12f">
<img width="2484" alt="2023-11-02_19-44-59" src="https://github.com/transfem-org/Sharkey/assets/161183/3f99c4d1-7a12-4035-bd2f-1f984502bcf4">

### 📝 Steps to Reproduce

1. Configure relays between two test servers (I used Activity-Relay, which is running on the first test Sharkey server at relaytest.tamaki-shimai.moe for a test)
2. Add the relay (e.g. https://relaytest.tamaki-shimai.moe/inbox) to both test servers. Refresh to make sure it says Accepted.
3. Type a public test message on the first and second test server.
4. Check the federated timelines to see if messages from both servers appear on the timeline without following each other (the relay receives posts from servers joined to the relay and sends it to all the servers joined in the relay). 

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11
* Browser: Chromium
* Server URL: localhost (test server is not publicly accessible)
* Misskey: 2023.11.0.beta3
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: shell script (test enviroment)
* Misskey:2023.11.0.beta3
* Node:v20.9.0
* PostgreSQL: 9.6
* Redis:6:7.2.3-1rl1~jammy1
* OS and Architecture: 22.04.3 LTS, x86-64
```

Relay shows both servers joined in the relay.
sharkey@sharkeytest1:~/Activity-Relay$ ./relay control domain list
WARN[0000] RELAY_ICON: INVALID OR EMPTY. THIS COLUMN IS DISABLED. 
WARN[0000] RELAY_IMAGE: INVALID OR EMPTY. THIS COLUMN IS DISABLED. 
 - Subscriber list :
[*] sharkeytest2.tamaki-shimai.moe
[*] sharkeytest1.tamaki-shimai.moe
 - Follower list :
Total : 2

**Comment by moyitpro** [comment]
I tried other Relay software in the local environment.

AodeRelay - Couldn't have the relay approve the request after adding it, don't think it's supported by Misskey
Fedi.buzz - it does kind of work, but posts do not show up automatically, had to refresh to get them to show.

Activity-Relay is the only real one that had support for Misskey, which was working before the recent changes and I can get working and it was working with 2023.10.2.

Of course, it took while to make a response to testing other software as I am busy, but this should be enough information to investigate the issue.

**Comment by ShittyKopper** [comment]
relay.fedi.buzz is working just fine* on my end, following 5 instances (2 of them being sharkey!) and 2 tags through it so far.

*: except the misskey-wide bug where everything it relays shows up as renotes

**Comment by Mar0xy** [comment]
For my instance which I setup a few days ago relay.fedi.buzz and rel.re(running aoderelay v0.3.104-HEAD-a0f9827e) work just fine.

**Comment by moyitpro** [comment]
@Mar0xy Thanks, Maybe I should look into switch relay software when I have the time to. The private relay I set up was there to join the Mastodon server I run with the Firefish server, and we also had one other Mastodon instance whom I am friends with the admin. The relay is private so only those I approve can join it.

Then again, I'm not sure if it's a bug with Activity-Relay as it was running on an older version, but it looks like the previous releases only updated the dependencies.

**Comment by Mar0xy** [comment]
Just tried out activity-relay and for some reason it only proceeds this far before not doing anything

![image](https://github.com/transfem-org/Sharkey/assets/8841466/67855d5a-029a-4775-87e6-554cd65581e7)

**Comment by Mar0xy** [comment]
Just tried it on a local environment and it resulted in a warn log about a bad request 
![image](https://github.com/transfem-org/Sharkey/assets/8841466/e6ab862b-fcd1-4077-9a13-63f7d4bf6ad8)
So there must be something going on in the background that causes it to mess up

**Comment by Mar0xy** [comment]
The issue with activity-relay seems like after having the follow request submitted successfully from sharkey it just proceeds to ignore it and and doesn't accept the follow resulting in sharkey also not getting updates from it nor being able to set it to approved so either a misskey update broke compatibility with it or an recent update to activity-relay broke it.

AodeRelay still worked fine after all my attempts on a dev instance.

I will leave this open for now so others can see it and chime in with more information if they got any

**Comment by moyitpro** [comment]
@Mar0xy I tried installing aoderelay (nrelay.sakurajima.moe) and I can't seem to get it accepted by the relay. Am I even using the right version, I'm using the one from the official repo.

<img width="824" alt="2023-11-13_18-41-40" src="https://github.com/transfem-org/Sharkey/assets/161183/e7fd80f8-fadd-4e13-ac53-a4ae743e1a3d">

**Comment by Mar0xy** [comment]
they show up as connected though 
![image](https://github.com/transfem-org/Sharkey/assets/8841466/0141891e-3a99-42e5-b78a-320accc1cc10)

**Comment by moyitpro** [comment]
Yes, it's strange since none of the messages are getting passed through the sharkey instance. 

Here is the .env file, I have the relay behind a proxy on a web server.

HOSTNAME=nrelay.sakurajima.moe
PORT=8082
HTTPS=false
DEBUG=false
RESTRICTED_MODE=true
VALIDATE_SIGNATURES=true
API_TOKEN=(redacted)
FOOTER_BLURB="Sakurajima Relay"
LOCAL_DOMAINS="sakurajima.moe"
LOCAL_BLURB=""
# OPENTELEMETRY_URL=http://localhost:4317
PROMETHEUS_ADDR=127.0.0.1
PROMETHEUS_PORT=9000

**Comment by Mar0xy** [comment]
I never really hosted a relay as I was always just looking at the output of the server running sharkey to see if it delivered the message and received an accepted message since `nrelay.sakurajima.moe` is restricted I am also not able to check it on my end with my `rant.lol` instance to see what happens exactly.

**Comment by moyitpro** [comment]
@Mar0xy I temporarily added this instance so you can test. Remove it after getting the output.

**Comment by Mar0xy** [comment]
Alright thanks I have now gotten my answer
![image](https://github.com/transfem-org/Sharkey/assets/8841466/eacfbc36-1163-4a72-b0c7-5d780501b360)

**Comment by Insert5StarName** [comment]
> Alright thanks I have now gotten my answer ![image](https://user-images.githubusercontent.com/8841466/282622669-eacfbc36-1163-4a72-b0c7-5d780501b360.png)

Didn't we have a similar issue with relays before?

**Comment by Mar0xy** [comment]
> > Alright thanks I have now gotten my answer ![image](https://user-images.githubusercontent.com/8841466/282622669-eacfbc36-1163-4a72-b0c7-5d780501b360.png)
> 
> Didn't we have a similar issue with relays before?

Not quite what is going on here is the fact that while the relay redirects to https for some reason the actual actor URL is not https causing it to get confused

**Comment by Mar0xy** [comment]
how it is suppose to be:
![image](https://github.com/transfem-org/Sharkey/assets/8841466/2339daeb-e586-4a6d-a0a3-5ca83bb8b633)


How it actually is:
![image](https://github.com/transfem-org/Sharkey/assets/8841466/84c74574-e5b4-436a-af48-d525a01ab385)

**Comment by Mar0xy** [comment]
So I wonder if simpy toggling HTTPS and readding the relay fixes it

**Comment by moyitpro** [comment]
Yes, that eventually does the trick, but the instance images on the relay page and the relay command is broken when HTTPS is turned on with aoderelay, it takes the hostname of the VPS instead of the one from the .env file. Might need to change the env file of the user that runs the relay. 

What I also notice is that the timeline doesn't automatically refresh when it gets new posts from a relay, and you have to refresh it. Is that normal behavior?

**Comment by Mar0xy** [comment]
> Is that normal behavior?

It is suppose to refresh unless the websocket disconnected or fan out timeline is disabled(which is a MK bug afaik)

**Comment by Mar0xy** [comment]
I will close this as it mainly turned out to just be an issue related to configuration of the relay.
The HTTPS redirection not being accepted when resolving actors for relays is a good thing in itself as HTTP to HTTPS redirections can include MITM attack if not properly handled by using HSTS.
