### ISSUE TITLE
posts are nyanified regardless of settings

### ISSUE THREAD

**Issue by tastytea** [transfem-org/Sharkey#134]
### 💡 Summary

words like “nazi” are turned into “nyazi” in outgoing posts, even if catmode is turned off.

first try to switch that off:
![image](https://github.com/transfem-org/Sharkey/assets/3681516/91c57610-6f40-4621-90b8-13f7aa92b95e)

second try to switch that off:
![image](https://github.com/transfem-org/Sharkey/assets/3681516/28c997cc-e3bb-4099-90f8-9be815c6fe3a)

it didn't work, even after clearing the cache.

### 🥰 Expected Behavior

text is not nyanified if “Speak as Cat” is turned off

### 🤬 Actual Behavior

text is nyanified if “Speak as Cat” and “Mark this account as cat” is turned off

### 📝 Steps to Reproduce

1. have “Speak as Cat” and “Mark this account as cat” turned on
2. turn them off
3. post `na`
4. look at post from mastodon

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Gentoo Linux (desktop)
* Browser: Firefox 115.4.0
* Server URL: https://very.tastytea.de/
* Misskey: Sharkey 2023.10.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: manual
* Misskey: Sharkey 2023.10.2
* Node: 20.6.1
* PostgreSQL: 15.4
* Redis: 7.2.1
* OS and Architecture: Gentoo Linux amd64
```

**Comment by Mar0xy** [comment]
This won't affect the next release at all since the nyaficiation was moved out of the note sending into a frontend only thing by misskey

**Comment by Mar0xy** [comment]
otherwise it always worked fine for everyone on transfem.social before so something might have been janky in your DB

**Comment by tastytea** [comment]
yeah, it worked after i restarted the instance :thinking:

**Comment by Mar0xy** [comment]
I will close this now though cause like stated above it no longer affects anything outside the sharkey/misskey instances and since you even stated that a restart fixed it
