### ISSUE TITLE
bug: posts are not showing as nya-ified in certain views

### ISSUE THREAD

**Issue by MoshiBar** [transfem-org/Sharkey#137]
### 💡 Summary

child and parent posts are not showing as nya-ified
in the reply compose view, the replied to text is also not nya-ified

### 🥰 Expected Behavior

the posts should be nya-ified

### 🤬 Actual Behavior

as shown below, the replied to text is not nya-ified
![image](https://github.com/transfem-org/Sharkey/assets/25570708/1351ce8e-526e-4e20-a55d-49d5139361a4)
as shown below, the child post is not nya-ified
![image](https://github.com/transfem-org/Sharkey/assets/25570708/ace7f07e-f446-4abd-92fc-8c0a3b36f25c)
as shown below, the parent post is not nya-ified
![image](https://github.com/transfem-org/Sharkey/assets/25570708/8f883ec6-b592-4821-a9f3-3b86f6829d90)

### 📝 Steps to Reproduce

N/A

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Arch Linux, GrapheneOS
* Browser: Firefox (Desktop and mobile tested)
* Server URL: ambrosia.moe
* Misskey: 13.x.x
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: 
* Misskey: Sharkey commit 9a73e98
* Node: v19.9.0
* PostgreSQL: docker
* Redis: docker
* OS and Architecture: Debian 11
```

**Comment by Insert5StarName** [comment]
this was fixed with https://github.com/transfem-org/Sharkey/commit/33f4e2eefab055e8d2abd5bd7b36a9945e4cc889 already
