### ISSUE TITLE
ListenBrainz status not appearing

### ISSUE THREAD

**Issue by MoshiBar** [transfem-org/Sharkey#14]
## 💡 Summary

ListenBrainz status not appearing when scrobbling to listenbrainz

## 🥰 Expected Behavior

Music status should appear on profile

## 🤬 Actual Behavior

Music status does not appear

this is the full console output when viewing my profile (i dont think its related but i thought i should include it anyway)
```
Misskey v2023.9.1.beta2 [app-52ebf1f4.js:35:34055](https://ambrosia.moe/vite/app-52ebf1f4.js)
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. [app-52ebf1f4.js:15:16788](https://ambrosia.moe/vite/app-52ebf1f4.js)
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. 2
```

my profile:
https://ambrosia.moe/@moshibar
my listenbrainz user:
moshibar

## 📝 Steps to Reproduce

1. add musicbrainz username to profile
2. played music, scrobbling to listenbrainz
3. Status not appearing on profile

## 📌 Environment

ambrosia.moe
commit aac4c8be6066c36c3c8a79558fe8af4fa2d97ffd

### 💻 Frontend
* Model and OS of the device(s):
  Arch Linux (also tested on Android)
* Browser:
  Firefox 118 (Flatpak)
  also tested on Vivaldi 6.1.3035.111
* Server URL:
  ambrosia.moe
* Misskey:
  v2023.9.1.beta2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: systemd
* Misskey: v2023.9.1.beta2
* Sharkey: commit aac4c8be6066c36c3c8a79558fe8af4fa2d97ffd
* Node: v19.9.0
* PostgreSQL: unsure, docker version
* Redis: unsure, docker version
* OS and Architecture: Debian 11

**Comment by Mar0xy** [comment]
It should work fine and fetch your currently playing song if the player/scrobbler even submits a playing_now even to listenbrainz.
If it doesn't then it obviously won't show up.

**Comment by MoshiBar** [comment]
yeah its submitting to listenbrainz, i can pull from their endpoint and the now playing status appears

**Comment by Mar0xy** [comment]
When scrobbling to ListenBrainz try opening dev tools and navigate to your instance's profile while viewing the network tab and then check the call towards the ListenBrainz API and check what it outputs and maybe share it here.

**Comment by Insert5StarName** [comment]
this issue is caused when the page is not in full desktop view

**Comment by Insert5StarName** [comment]
fixed in latest release
