### ISSUE TITLE
make träwelling masto integration (/oauth/decision) work

### ISSUE THREAD

**Issue by tastytea** [transfem-org/Sharkey#148]
### Summary

it would be nice if https://traewelling.de/ would work with the Mastodon API emulation. 💖 currently i get this error after clicking accept on the oauth authorization dialog:

```json
{
  "message": "Route POST:/oauth/decision not found",
  "error": "Not Found",
  "statusCode": 404
}
```

it does work with firefish, don't know if that's helpful 😊

**Comment by Mar0xy** [comment]
I will add this endpoint later

**Comment by CutestNekoAqua** [comment]
firefish is a 50/50 to work, yall

**Comment by tastytea** [comment]
> I just checked and it seem firefish does not implement this endpoint either.

someone on firefish said it worked :thinking:

**Comment by Mar0xy** [comment]
Fixed the issue was caused by träwelling adding an / at the end and fastify being fastify thinking it was a different endpoint immediately

![image](https://github.com/transfem-org/Sharkey/assets/8841466/05297ab6-6fd7-4259-bf4b-2f7ebc9a912a)

**Comment by tastytea** [comment]
thank you! 💖

**Comment by tastytea** [comment]
it worked on 2023-11-09, but when i had to redo the linking of the account on 2023-11-19 it didn't work anymore. all i get is “An error has occured” right after logging in. i did not change anything in my installation, it's sharkey 2023.11.0 + 2fae63f + 885800e + d94b1c3

<details><summary>screenshot</summary>

![Screenshot_20231122-105413_Firefox](https://github.com/transfem-org/Sharkey/assets/3681516/c9e7ba02-312d-4cf3-8388-9b44ac4d7d40)

</details>

**Comment by Mar0xy** [comment]
I have realized this a while back but this is not at all related to the integration it is related to it just generally being broken once the apps get removed with it just never recreating them causing it to always error out the only solution I found so far was to make the app each time /oauth/authorize was called but this would come at the downside of it always making a new app.

**Comment by tastytea** [comment]
i see. is there a way to manually fix that?  
i looked around in the database and found that there is an entry for träwelling in the “app” table but deleting that didn't do anything useful… :thinking:
