### ISSUE TITLE
docs: Guide to migrate from firefish to Sharkey

### ISSUE THREAD

**Issue by RoxyBoxxy** [transfem-org/Sharkey#15]
## Summary

Create a guide to migrate from firefish to sharkey, firefish is using a older version of misskey but has had some tweeks not sure what fork this is using 

thanks

**Comment by Insert5StarName** [comment]
sharkey is forked directly from Misskey, if you want to migrate to Sharkey from Firefish contact me on discord and i can help you currently specific guides will still have to be written

**Comment by Insert5StarName** [comment]
my discord user name is apparmor

**Comment by Mar0xy** [comment]
> contact me on discord and i can help you currently specific guides **will still have to be written**

It seems like you skipped over the first section saying this "Create a guide"

**Comment by Insert5StarName** [comment]
yeah im planning to make a guide but i need more data to make one we currently only migrated a firefish instance once

**Comment by Kio-td** [comment]
## Migrating Firefish to Sharkey.
This guide focuses on docker variants only.

* Do not use Sharkey if you have already moved to ScyllaDB. You must be on Postgres to be able to migrate right now.
* You'll need to revert to using DeepL if you were using the LibreTranslate system.
* Sonic is no longer used for searching.


1. Stop your old instance.
(Make sure to let your users know, of course.)
2. Modify your volumes. All volumes beginning with `/firefish/` should be changed to `/sharkey/`.
3. Run the following postgresql using `psql`, NOT using an online panel.
```sql
CREATE TABLE antenna_note();
ALTER TABLE "user" 
DROP COLUMN "movedToUri";
ALTER TABLE "user" 
DROP COLUMN "alsoKnownAs";
ALTER TABLE "user_profile" 
DROP COLUMN "preventAiLearning";
ALTER TABLE "meta" RENAME COLUMN "ToSUrl" TO "termsOfServiceUrl";
ALTER TYPE "public"."user_profile_mutingnotificationtypes_enum" ADD VALUE 'note';
DELETE FROM moderation_log WHERE info = '{}';
ALTER TABLE "user"
DROP COLUMN "speakAsCat";
--- Update Antenna Types
CREATE TYPE public.new_antenna_src_enum AS ENUM ('home', 'all', 'list');
ALTER TABLE antenna ADD COLUMN new_src public.new_antenna_src_enum;
DELETE FROM antenna
WHERE src NOT IN ('home', 'all', 'list');
ALTER TABLE antenna DROP COLUMN src;
ALTER TABLE antenna RENAME COLUMN new_src TO src;
DROP TYPE public.antenna_src_enum;
ALTER TYPE new_antenna_src_enum RENAME TO antenna_src_enum;
```
