### ISSUE TITLE
fix link to access avatar decorations

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#150]
### 💡 Summary

For non-priviledged users with role-access to avatar-decorations,

A user who clicks on the button on tools-> manage avatar decorations
Brings you to https://shark.ey/admin/avatar-decorations - a 404 page.

### 🥰 Expected Behavior

Users can make modifications.

### 🤬 Actual Behavior

404 error.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Mar0xy** [comment]
>  role-access to avatar-decorations

This is intended behaviour as this option only lets users use avatar decorations on their profile and isn't meant to allow them to modify/add them.

**Comment by Kio-td** [comment]
Uh? I have to disagree, or the wording needs to be changed...
![Screenshot_20231108_175636_Chrome](https://github.com/transfem-org/Sharkey/assets/7786316/f609791f-a05b-4ea6-8cbd-d15703ff1653)

**Comment by Insert5StarName** [comment]
> > role-access to avatar-decorations
> 
> This is intended behaviour as this option only lets users use avatar decorations on their profile and isn't meant to allow them to modify/add them as that privilege is exclusive to admins.

well its true but then again u can give a role privilegeds to access avatar decs same with custom emojis
