### ISSUE TITLE
feat: Timeline sorting

### ISSUE THREAD

**Issue by flexstrongo** [transfem-org/Sharkey#158]
### Summary

There's a great feature in [Streams](https://codeberg.org/streams/streams) to order your timeline by Posted Date, Commented Date, Received Date, or Unthreaded.

Posted Date is what Sharkey defaults to currently, I think. Where a post is received and added to the top of the timeline. 

Commented Date will push a post to the top of the timeline if a new comment is received on that post.  This is what I'd really like to see implemented.  Being able to sort the timeline posts as new comments are received would keep lively conversations up near the top of your timeline, and seems to keep people more involved in their feeds. 

![image](https://github.com/transfem-org/Sharkey/assets/1082408/4726da03-0014-4956-8dce-53f5f3014c0f)

**Comment by Mar0xy** [comment]
I have been thinking about this actively for the last 2 weeks and while this sounds nice at first it got into the section of "but what if someone constantly comments on their own post to keep it up" and "is it really worth trying to keep this feature functional with each upstream merge" which ultimately made me decide against this as Misskey in itself was meant to be a micro blogging platform and normally something like this would be out of scope for it.
