### ISSUE TITLE
I can't post using Misskey API.

### ISSUE THREAD

**Issue by MizuiMiduki** [transfem-org/Sharkey#162]
I can't post using Misskey's API endpoint.Has the endpoint etc. changed in Sharkey?(Using Google Translate)

**Comment by MizuiMiduki** [comment]
This issue has been reported by users of tools I develop for Misskey and its derivative services. 
You can post with other derived services, but it seems like you can't post with Sharkey.

We would like to resolve this issue, so please help us.

**Comment by Mar0xy** [comment]
Sharkey never did any changes to the way posting works from Misskey API and works fine with other tools that Implement Misskey API like Kaiteki.

If this really is an issue with Sharkey then I would need to know the tools having these issues to investigate further.

**Comment by MizuiMiduki** [comment]
thank you for your reply.
I applied to register with TransFem Space, so I'll do some research there.
I'll report back if anything happens.
