### ISSUE TITLE
bug: unhelpful error when submitting an invalid emoji name

### ISSUE THREAD

**Issue by MoshiBar** [transfem-org/Sharkey#163]
### 💡 Summary

when creating an emoji, or editing an existing emoji, if a name with an invalid character is used, an unhelpful error is shown
![image](https://github.com/transfem-org/Sharkey/assets/25570708/679b621d-888f-4cf8-98b0-d8b473ffbb3f)

### 🥰 Expected Behavior

message should be helpful, maybe give an error message saying which characters are unable to be used

### 🤬 Actual Behavior

an unhelpful error message is shown, as described above

### 📝 Steps to Reproduce

1. create an emoji or edit an existing emoji, and give it an invalid name: e.g. using a period or hyphen
2. hit the update button, the error message should show

### 💻 Frontend Environment

* Model and OS of the device(s): Fedora Kinoite
* Browser: Firefox flatpak
* Server URL: ambrosia.moe
* Misskey: 13.x.x

### 🛰 Backend Environment (for server admin)

* Installation Method or Hosting Service: baremetal
* Misskey: commit 42bf8e5e76fb6a6dce804c1784e1e2833268c1e6
* Node: 20.4.0
* PostgreSQL: docker
* Redis: docker
* OS and Architecture: Debian 11 x86_64

**Comment by Mar0xy** [comment]
This is an error that gets returned by the router and not the software as the add endpoint uses a pattern check for numbers and normal characters (including underscores) provided to the router to check if the request parameter is valid if it has an invalid character it will throw an invalid parameter error which triggers this error.

tl:dr

This is intended and not a bug and no it won't be changed as it exactly explains what happened
