### ISSUE TITLE
bug: PWA does not follow instance's icon

### ISSUE THREAD

**Issue by abUwUser** [transfem-org/Sharkey#165]
### 💡 Summary

The PWA, when added, does not display the instance's icon. This may annoy users due to Sharkey's icon not being abstract, looking off with other abstract icons from other applications
As you can see over here, the instance's favicon is different from the PWA icon
![image](https://github.com/transfem-org/Sharkey/assets/27961224/8604c469-5b3e-481a-809b-0f123d64c863)
Looking at the [manifest.json of Kitsunes.club](https://kitsunes.club/manifest.json), both the 192x192 and the 512x512 sizes uses the instance's logo, but the 300x300 icon, marked with the `"purpose":"any"` key uses Sharkey's default logo. I do not know if it is configurable on the instance's part, but if the instance's icon is used for the other icon sizes, then it should be on the 300x300 one

### 🥰 Expected Behavior

The 300x300 icon should match with the instance's icon

### 🤬 Actual Behavior

The 300x300 icon does not match with the instance's icon

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Fedora Linux 39
* Browser: Thorium
* Server URL: https://kitsunes.club
* Misskey: 2023.11.0
```

**Comment by Mar0xy** [comment]
The PWA does actually follow the instance icon when installed on a phone/tablet why misskey never considered having another field for it is since you need to provide every icon in the appropriate size so they just skipped the unimportant one which imo is an okay thing to do since PWAs on PC are kinda meh situation in the first place.

![image](https://github.com/transfem-org/Sharkey/assets/8841466/4a0b00d0-7778-4c53-8a06-8baabacdef84)

I will leave this open for other peoples opinions but my opinion is as stands.

**Comment by abUwUser** [comment]
> imo is an okay thing to do since PWAs on PC are kinda meh situation in the first place. 

I do believe that PWAs on PC are useful for me since it helps with the clutter of tabs on my browser. It is easier to find and manage an application in a windowed system than a tab in a browser

> Also considering chromium is the only engine that benefits from this as every other browser does not support PWAs on Desktop

You can add PWAs to Firefox using FirefoxPWA. Also, chromium is the one that has the majority of users in the world, so the argument falls flat since it is not a minority. Also most chromium based web browsers still maintain their PWA support

**Comment by Mar0xy** [comment]
> It is easier to find and manage an application in a windowed system than a tab in a browser

You do realize separating tabs into windows is a possibility?

> You can add PWAs to Firefox using FirefoxPWA

And this already involves a third party which has the ability to do MITM attacks if you don't watch out as well as the fact that features can be missing.

**Comment by abUwUser** [comment]
> You do realize separating tabs into windows is a possibility so that argument also falls flat cause at that point you are literally doing the same Thing.

It is a possibility, but one thing is a browser window with tabs, other thing is a window that looks like application. Just look at Discord, why install the app if there's the browser version?

> And this already involves a third party which has the ability to do MITM attacks if you don't watch out as well as the fact that features can be missing.

That's a fair point
<br>
Uh ...
Honestly, why are we arguing about PWA's usefulness? At the end it is a bug as the icon should be consistent between desktop and mobile (also ngl installing PWAs on mobile sucks). I guess the debate here is if we should let instances choose the icon or to always be Sharkey's default icon
