### ISSUE TITLE
bug: Classic View is broken

### ISSUE THREAD

**Issue by Freeplayg** [transfem-org/Sharkey#172]
### 💡 Summary

Sidebars are not stuck to the sides when scrolling down

I was also wondering if it would be possible to do sort of do the same thing I had done in these pull requests ?
https://codeberg.org/firefish/firefish/pulls/10097
https://codeberg.org/firefish/firefish/pulls/10122

### 🥰 Expected Behavior

sidebars should have position fixed or sticky

### 🤬 Actual Behavior

![image](https://github.com/transfem-org/Sharkey/assets/40742947/3b8535e3-e619-4d8d-99e3-027e3f6562e8)

### 📝 Steps to Reproduce

scroll down

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Fedora 36, Gnome
* Browser: Firefox
* Server URL: plasmatrap.com
* Misskey: Sharkey v2023.11.2.beta1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Insert5StarName** [comment]
seems like this should be a simple fix, i can also look into porting the pr's over tho it might be more difficult do to the fact misskey v13 fe is very different to misskey v12 fe
