### ISSUE TITLE
Attempting to select text in a post, opens the post

### ISSUE THREAD

**Issue by Freeplayg** [transfem-org/Sharkey#175]
### 💡 Summary

This is some code from my own project that may help with this (the matchMedia if statement is unrelated):
![image](https://github.com/transfem-org/Sharkey/assets/40742947/0f5a64b6-11b6-4fde-ac10-525151ee22d1)
![image](https://github.com/transfem-org/Sharkey/assets/40742947/836c0946-3076-4a69-a962-a71f0ed7c52a)
the `on:event` is just an event listener in Svelte

### 🥰 Expected Behavior

Selecting text should not open the post

### 🤬 Actual Behavior

It opens the post
[Screencast from 2023-11-27 15-30-24.webm](https://github.com/transfem-org/Sharkey/assets/40742947/01638a43-d5bf-4e52-9131-b3b70574b451)

### 📝 Steps to Reproduce

Select some text on a post in a timeline (not opened)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Fedora 36, Gnome
* Browser: Firefox 120.0
* Server URL: plasmatrap.com
* Misskey: Sharkey v2023.11.2.beta1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Mar0xy** [comment]
> the on:event is just an event listener in Svelte

vue's v-on:click/@click is also just an event listener for listening to clicks but for some reason vue also registers clicking and selecting as a click

**Comment by Mar0xy** [comment]
I guess one way to fix this is by checking if text is selected.

**Comment by Mar0xy** [comment]
Yup, this indeed solved the issue in the vue playground will fix this real quick.

**Comment by Freeplayg** [comment]
> I guess one way to fix this is by checking if text is selected.
Yea that's what the checkSelecting function does on a pointerdown event
`selecting = document.getSelection()?.type === "Range";`

**Comment by Mar0xy** [comment]
> Yea that's what the checkSelecting function does on a pointerdown event selecting = document.getSelection()?.type === "Range";

I have basically done the exact same thing now just instead of getting type I check if selection doesn't have anything at all since it is empty if there is no selection done.
