### ISSUE TITLE
feat: Search bar widget

### ISSUE THREAD

**Issue by Freeplayg** [transfem-org/Sharkey#181]
### Summary

Adding a search bar to the top of the widgets sidebar (probably by default)

### Purpose

Having search on a completely separate page really isn't great, I think having an easily accessible search bar would make things a lot easier. Especially since you're probably going to be loading posts from other instances a lot as you won't have to go through an extra page.

The search shortcut (s) should also just focus that bar if added

**Comment by Mar0xy** [comment]
Currently opening search in a window is a possibility though a widget is something that can be added as an option just would need to look into how widgets function. (though the widget will only be for searching normally with no filters then as to not make a cluttered widget)

**Comment by Freeplayg** [comment]
To have it not be too cluttered, maybe all the filters could be under one button like Firefish does ?
![image](https://github.com/transfem-org/Sharkey/assets/40742947/60f0be05-b397-4ffb-ad44-694c942a2b0c)

**Comment by Mar0xy** [comment]
Well there really are only two filters:

1. With file
2. From user

I guess this could be a possibility for the widget but I would need to look into how dropdown selections work on MIsskey.

Mastodon's option is out of the race as I would rather keep consistency with MK which uses a folder for the filters on search page
