### ISSUE TITLE
feat: Make visible if a poll is multiple choice

### ISSUE THREAD

**Issue by theresmiling** [transfem-org/Sharkey#182]
### Summary

It would be great if it were possible to see if a poll is single or multiple choice. Right now all I see are the options, but I don‘t know if I can click only one or multiple of them.

E.g. on Mastodon circles indicate single choice, squares indicate multiple choice. In Sharkey we only have bars.

Thank you!

### Purpose

I would like to know if I can vote for only one or multiple options. That would make it easier to decide what to vote for. Also, the results would be more accurate if I knew I could vote for multiple items.

**Comment by Mar0xy** [comment]
I wonder if an indicator below the options would be good enough (where the ending timestamp and etc are)

**Comment by diziara** [comment]
I'm of mixed thought on if it would be? I suppose it would depend on how you all implement it. If it's the same size and font weight/style as the other info, it stands a chance of sliding past users notice, but if it's bigger and maybe bold, that might be okay?

Basically, can it pass an ADHDer in a hurry low on spoons test?

**Comment by Mar0xy** [comment]
the main reason I want to do it like that is cause adding buttons and etc would require going off course a lot from the original code making it harder to work around for something like a soft-fork

**Comment by diziara** [comment]
> the main reason I want to do it like that is cause adding buttons and etc would require going off course a lot from the original code making it harder to work around for something like a soft-fork

A notice at the bottom isn't incompatible with my needs, I'm just saying to be mindful of the style and placement so it doesn't blend into the other info down there. Because of the poor upstream choice here, it puts you in a bit of a difficult position. The "correct" solution that brings these polls in line with standard UI choices sounds like a lot of work for you both short and long term if I'm understanding you correctly, so I get your hesitation to go that route.

**Comment by Mar0xy** [comment]
I might just do the pop-up option dakkar talked about and then also add a notice below the poll which fits in with the rest of the text at the bottom cause otherwise it would look off.

**Comment by Insert5StarName** [comment]
> I might just do the pop-up option dakkar talked about and then also add a notice below the poll which fits in with the rest of the text at the bottom cause otherwise it would look off.

seems like the best option
