### ISSUE TITLE
feat: Provide MFM Cheatsheet in selected language

### ISSUE THREAD

**Issue by justdaj** [transfem-org/Sharkey#183]
### Summary

The MFM Cheat sheet, which you can access when creating a new Note, only has English text.

It would be goof to have specific language text, based on the users Language settings 

### Purpose

This will help complete the localised experience

**Comment by Mar0xy** [comment]
It already is localized just obviously there are only english locales as they need to be translated by people:
https://github.com/transfem-org/Sharkey/blob/develop/locales/en-US.yml#L2284-L2356
