### ISSUE TITLE
Problems with sharkey federation

### ISSUE THREAD

**Issue by HelgeKrueger** [transfem-org/Sharkey#190]
So, I've tried adding sharkey to my [fediverse pasture](https://funfedi.dev/fediverse_pasture/), and first steps where easy. So I got sharkey running and talking to other applications on some levels, after setting the environment variable:

```
MISSKEY_WEBFINGER_USE_HTTP: true
```

Unfortunately, then the problems started. First, I decided to use a lower case "sha256" in my code (as done for example [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest#examples) ). I was able to patch this, see

https://codeberg.org/helge/funfedidev/commit/23e418ea11f06abf6bc293acba5675c08b17b349

Now I'm running into trouble because the request for an actor object does not appear to be signed. Is that a known issue with all MissKey forks? Is it something that might be easy to fix?

Also is there a way to add a lot of logging? I tried

```
MK_VERBOSE: true
MK_WITH_LOG_TIME: true
```

but this doesn't seem to generate the amount of log output, I would like.

Thanks!

**Comment by Mar0xy** [comment]
in the patch file it says

`if (algo !== 'SHA-256' && algo !== 'sha-256')`

But shouldn't it be

`if (algo !== 'SHA-256' || algo !== 'sha-256')`

> Now I'm running into trouble because the request for an actor object does not appear to be signed

This is something MK recently added as a security measure cause it was missing up to this point see this CVS https://github.com/misskey-dev/misskey/security/advisories/GHSA-3f39-6537-3cgc

Generally speaking MK also prefers running in HTTPS in a nutshell

> Also is there a way to add a lot of logging? I tried

There isn't as most logging is only possible when running in a dev environment via the dev script in package.json

**Comment by Mar0xy** [comment]
I will close this issue as per the merge on https://codeberg.org/helge/funfedidev/commit/587af4cead00aba05c652c49b6646f9aaa7c2bc8
