### ISSUE TITLE
feat: Backfill replies and reactions to posts from other instances ("FediFetcher"-like behavior)

### ISSUE THREAD

**Issue by minneyar** [transfem-org/Sharkey#205]
### Summary

Add the ability to either periodically or on-demand retrieve replies and reactions to posts received from other fediverse instances, or retrieve posts of remote users from before they were first known to the local instance.

### Purpose

A common problem on smaller instances is that you will receive posts from remote users who are followed by local users, but you may not receive replies or reactions to those posts from other remote users.  This can leave conversations feeling patchy or empty, and viewing the original post on its original instance may reveal that there is a long thread of posts that you cannot see or interact with locally because you never received them.

Another problem is that when a remote user is followed for the first time, the only posts you can see on their profile are their pinned posts and any new posts they make after that point; you'll never see their older posts unless they boost them, which is frustrating if there was a specific post you found that made you follow them, and you want to be able to boost it.

[FediFetcher](https://github.com/nanos/FediFetcher) is a script that alleviates this problem for Mastodon by running periodically to retrieve remote replies & reactions from other instances.  It would be great for Sharkey to support this functionality.

Supposedly it uses the Mastodon API, so it *may* work with Sharkey -- I admit I haven't tried it because I don't have a Sharkey instance, but it does not work with Firefish.  If it does work with Sharkey, I feel like it should be advertised somewhere, because IMO this is a killer feature, and I would immediately migrate to Sharkey for it.  Even if it does, it would also be great if this behavior was integrated into Sharkey itself so that it could be configured through Sharkey's web interface instead of requiring an admin to set up a cron job, which is also a little awkward since it requires an access token for each local user.

**Comment by Mar0xy** [comment]
> Supposedly it uses the Mastodon API, so it may work with Sharkey -- I admit I haven't tried it because I don't have a Sharkey instance

There are users happily using FediFetcher without issues.

**Comment by Mar0xy** [comment]
> I guess that's because of missing API endpoints for moderation stuff.

We generally don't have any admin endpoints and don't plan on providing some since they aren't really needed in most case and also cause there is mainly an overall plan to eventually (maybe in 50 years /j) rewrite the mastodon api.
