### ISSUE TITLE
feat: Federation over proxy

### ISSUE THREAD

**Issue by ch0ccyra1n** [transfem-org/Sharkey#211]
### Summary

I think it would be great to add support for using a proxy for outgoing connections (i.e. federation). As I understand it, neither Misskey nor any of its forks actually allow you to do this as an admin, or if they do it's very poorly documented.

### Purpose

My particular use-case for this is to federate with some fediverse instances which only exist on [Tor](https://torproject.org). It's a concept I'm very passionate about because one of the downsides to the current way the fediverse works is that people are required to have a domain name in order to create a server. Allowing federation over Tor (or any proxy) would improve interoperability between more instances.

For examples of this in other fediverse software:
- [Pleroma](https://docs.pleroma.social/backend/configuration/onion_federation/)
- [Mastodon](https://gist.github.com/hcmiya/e635b31ae8c4b33d903f224ddbc45197)

**Comment by Mar0xy** [comment]
This is out of scope for this project but misskey does support being hosted on tor via nginx proxy which also applies to sharkey see this japanese post about it: https://blog.moe233.net/posts/2246a551/

**Comment by ch0ccyra1n** [comment]
Interesting! I suppose it might be something which would be good to translate and bring over to the Sharkey documentation. Closing this issue since as you stated it's already possible.

**Comment by Mar0xy** [comment]
> Interesting! I suppose it might be something which would be good to translate and bring over to the Sharkey documentation. Closing this issue since as you stated it's already possible.

Might be worth doing in the future.

**Comment by dakkar** [comment]
To be clear: that post describes how to *serve* a misskey instance over Tor. That's *inbound* connections: the rest of Tor talking to your *key.

If what you want is to proxy *outbound* connections (your *key instance talking to the rest of the Internet/Tor), https://github.com/transfem-org/Sharkey/blob/develop/.config/example.yml#L180-L192 these are the relevant bits of configuration

Yes, you don't get to say "use the proxy for this remote instance but not for this other one". If you need that, configure your proxy to route requests differently based on the remote host.
