### ISSUE TITLE
Icons do not work specifically on Firefox Nightly for Mobile

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#24]
## 💡 Summary
No icon is able to load.

## 🥰 Expected Behavior
![Screenshot_20230930_100822_Firefox](https://github.com/transfem-org/Sharkey/assets/7786316/cffee353-cda8-4cf9-aeee-96fa37452b0b)

## 🤬 Actual Behavior
![Screenshot_20230930_100829_Firefox Nightly](https://github.com/transfem-org/Sharkey/assets/7786316/c559edd7-bdec-49f4-85ba-3e5d48bc7c33)

## 📝 Steps to Reproduce

1. Use Firefox Nightly for Android.

### 💻 Frontend
* Model and OS of the device(s):
  
Z Fold5.
* Browser:
   Firefox Nightly 120.0a1
* Server URL:
   anon
* Misskey:
2023.9.1.beta2

**Comment by Kio-td** [comment]
Related:
https://github.com/tabler/tabler-icons/issues/476
https://github.com/webcompat/web-bugs/issues/118081

**Comment by Insert5StarName** [comment]
this is currently actively being worked on sadly this does involve changing the icon font as its not spec compliant (thanks misskey)

**Comment by Insert5StarName** [comment]
fixed in latest dev branch closing issue
