### ISSUE TITLE
Autopopulate user settings on Migrated user Setup

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#28]
## Summary
If an instance migrates to Sharkey, the users should be able to hit the floor running.

If there have not been changes since moving, the setup prompt should be automatically skipped.

Specifically for ff->sk migrations, it may be better to customize the setup prompt to show people the new features they have access to, instead of requiring account setup.

Currently, the setup menu requires the user to reinitialize if they don't skip, which may make them lose important settings, like "followers require approval", which has happened to one of my users already.

**Comment by Mar0xy** [comment]
the setup screen is mainly controlled by the state stored in an account as migrating adds new stuff including that state it is basically near to impossible to prevent it from happening without breaking new setups

**Comment by Kio-td** [comment]
Fair point! Is there a specific area in the actual DB itself that I can change?

**Comment by Mar0xy** [comment]
in the table `registry_item` you can see entries with a userId followed by a key with `accountSetupWizard` set as value -1 you can go and add all your users into that table with those same attributes as scope, key and value to disable it for each user already existing

**Comment by Mar0xy** [comment]
I will close this as there is nothing much to be added here.
