### ISSUE TITLE
bug: Automatic Reconnection traps browser in the site

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#43]
## Summary
In the event Sharkey disconnects from the server, and it's possible to reconnect, Sharkey should just reconnect, reporting the last event it has received and getting caught up from there.

**Comment by Insert5StarName** [comment]
this already exists in settings but is currently not default as it traps your browser to the instance as if u try to leave the instance it gets a disconnect event and resets the connection

**Comment by Kio-td** [comment]
Now that you mention it, that was a problem with Firefish, firefox was constantly trapped on both instances, forcing me to close the connection. Is there any logic that can be added to tell the FE to go offline and stay offline?

**Comment by Insert5StarName** [comment]
that is what we are trying to figure out tho currently its lower priority than some other tasks

**Comment by Kio-td** [comment]
Best place to start would be ``window.unbeforeunload``, and setting some sort of variable the disengages automatic reconnection.

**Comment by Insert5StarName** [comment]
even on latest commit it still traps the browser

**Comment by Mar0xy** [comment]
then dont have it on as it isn't needed anymore
