### ISSUE TITLE
Feature Request: Ubuntu Bash Script Install Support

### ISSUE THREAD

**Issue by alcapurrias** [transfem-org/Sharkey#47]
## Summary

I would love to install Sharkey but I've always installed Misskey and its forks with the Ubuntu scripts. It would be awesome if y'all ported [Misskey's](https://github.com/joinmisskey/bash-install) to work for Sharkey as well.

**Comment by Mar0xy** [comment]
I have tried converting their bash script you can find it at https://github.com/transfem-org/bash-install tell me here if you run into any issues

**Comment by alcapurrias** [comment]
Awesome, thank you! It did error out on the megalodon build step, but everything up to that point was working perfectly:

Process: build Sharkey;

> sharkey@2023.9.1.beta3 build /home/sharkey/sharkey
> pnpm build-pre && pnpm -r build && pnpm build-assets

> sharkey@2023.9.1.beta3 build-pre /home/sharkey/sharkey
> node ./scripts/build-pre.js

Scope: 5 of 6 workspace projects
packages/megalodon build$ tsc -p ./
│ src/friendica.ts(3,29): error TS7016: Could not find a declaration file for…
│   Try `npm i --save-dev @types/parse-link-header` if it exists or add a new…
│ src/friendica/api_client.ts(2,30): error TS7016: Could not find a declarati…
│   Try `npm i --save-dev @types/object-assign-deep` if it exists or add a ne…
│ src/mastodon.ts(3,29): error TS7016: Could not find a declaration file for …
│   Try `npm i --save-dev @types/parse-link-header` if it exists or add a new…
│ src/mastodon/api_client.ts(2,30): error TS7016: Could not find a declaratio…
│   Try `npm i --save-dev @types/object-assign-deep` if it exists or add a ne…
│ src/misskey/web_socket.ts(3,28): error TS7016: Could not find a declaration…
│   Try `npm i --save-dev @types/uuid` if it exists or add a new declaration …
│ src/pleroma/api_client.ts(2,30): error TS7016: Could not find a declaration…
│   Try `npm i --save-dev @types/object-assign-deep` if it exists or add a ne…
│ test/integration/cancel.spec.ts(2,24): error TS2307: Cannot find module 'je…
│ test/integration/cancel.spec.ts(4,1): error TS2304: Cannot find name 'jest'.
│ test/integration/cancel.spec.ts(5,21): error TS2304: Cannot find name 'jest…
│ test/integration/cancel.spec.ts(31,1): error TS2582: Cannot find name 'desc…
│ test/integration/cancel.spec.ts(33,3): error TS2582: Cannot find name 'it'.…
│ test/integration/cancel.spec.ts(36,11): error TS2304: Cannot find name 'exp…
│ test/integration/detector.spec.ts(3,1): error TS2582: Cannot find name 'des…
│ test/integration/detector.spec.ts(4,3): error TS2582: Cannot find name 'des…
│ test/integration/detector.spec.ts(6,5): error TS2582: Cannot find name 'it'…
│ test/integration/detector.spec.ts(8,7): error TS2304: Cannot find name 'exp…
│ test/integration/detector.spec.ts(12,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(14,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(16,7): error TS2304: Cannot find name 'ex…
│ test/integration/detector.spec.ts(20,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(22,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(24,7): error TS2304: Cannot find name 'ex…
│ test/integration/detector.spec.ts(28,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(30,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(32,7): error TS2304: Cannot find name 'ex…
│ test/integration/detector.spec.ts(36,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(38,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(40,7): error TS2304: Cannot find name 'ex…
│ test/integration/detector.spec.ts(44,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(46,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(48,7): error TS2304: Cannot find name 'ex…
│ test/integration/detector.spec.ts(52,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(54,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(56,7): error TS2304: Cannot find name 'ex…
│ test/integration/detector.spec.ts(60,3): error TS2582: Cannot find name 'de…
│ test/integration/detector.spec.ts(62,5): error TS2582: Cannot find name 'it…
│ test/integration/detector.spec.ts(64,13): error TS2304: Cannot find name 'e…
│ test/integration/mastodon.spec.ts(7,1): error TS2304: Cannot find name 'jes…
│ test/integration/mastodon.spec.ts(147,1): error TS2582: Cannot find name 'd…
│ test/integration/mastodon.spec.ts(187,5): error TS2582: Cannot find name 'i…
│ test/integration/mastodon.spec.ts(200,7): error TS2304: Cannot find name 'e…
│ test/integration/mastodon.spec.ts(203,3): error TS2582: Cannot find name 'i…
│ test/integration/mastodon.spec.ts(216,5): error TS2304: Cannot find name 'e…
│ test/integration/mastodon/api_client.spec.ts(6,1): error TS2304: Cannot fin…
│ test/integration/mastodon/api_client.spec.ts(92,1): error TS2582: Cannot fi…
│ test/integration/mastodon/api_client.spec.ts(101,3): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(104,5): error TS2304: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(108,1): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(117,3): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(122,5): error TS2304: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(126,1): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(135,3): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(140,5): error TS2304: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(144,1): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(153,3): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(158,5): error TS2304: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(162,1): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(171,3): error TS2582: Cannot f…
│ test/integration/mastodon/api_client.spec.ts(174,5): error TS2304: Cannot f…
│ test/integration/misskey.spec.ts(7,1): error TS2304: Cannot find name 'jest…
│ test/integration/misskey.spec.ts(137,1): error TS2582: Cannot find name 'de…
│ test/integration/misskey.spec.ts(187,5): error TS2582: Cannot find name 'it…
│ test/integration/misskey.spec.ts(200,7): error TS2304: Cannot find name 'ex…
│ test/integration/misskey.spec.ts(203,3): error TS2582: Cannot find name 'it…
│ test/integration/misskey.spec.ts(216,5): error TS2304: Cannot find name 'ex…
│ test/integration/pleroma.spec.ts(7,1): error TS2304: Cannot find name 'jest…
│ test/integration/pleroma.spec.ts(151,1): error TS2582: Cannot find name 'de…
│ test/integration/pleroma.spec.ts(191,5): error TS2582: Cannot find name 'it…
│ test/integration/pleroma.spec.ts(204,7): error TS2304: Cannot find name 'ex…
│ test/integration/pleroma.spec.ts(207,3): error TS2582: Cannot find name 'it…
│ test/integration/pleroma.spec.ts(220,5): error TS2304: Cannot find name 'ex…
│ test/unit/mastodon.spec.ts(1,1): error TS2582: Cannot find name 'describe'.…
│ test/unit/mastodon.spec.ts(2,3): error TS2582: Cannot find name 'it'. Do yo…
│ test/unit/mastodon.spec.ts(4,5): error TS2304: Cannot find name 'expect'.
│ test/unit/mastodon/api_client.spec.ts(7,1): error TS2582: Cannot find name …
│ test/unit/mastodon/api_client.spec.ts(8,3): error TS2582: Cannot find name …
│ test/unit/mastodon/api_client.spec.ts(9,5): error TS2582: Cannot find name …
│ test/unit/mastodon/api_client.spec.ts(10,7): error TS2582: Cannot find name…
│ test/unit/mastodon/api_client.spec.ts(42,11): error TS2304: Cannot find nam…
│ test/unit/mastodon/api_client.spec.ts(46,5): error TS2582: Cannot find name…
│ test/unit/mastodon/api_client.spec.ts(47,7): error TS2582: Cannot find name…
│ test/unit/mastodon/api_client.spec.ts(75,11): error TS2304: Cannot find nam…
│ test/unit/misskey/api_client.spec.ts(17,1): error TS2582: Cannot find name …
│ test/unit/misskey/api_client.spec.ts(18,3): error TS2582: Cannot find name …
│ test/unit/misskey/api_client.spec.ts(19,5): error TS2582: Cannot find name …
│ test/unit/misskey/api_client.spec.ts(20,7): error TS2582: Cannot find name …
│ test/unit/misskey/api_client.spec.ts(52,11): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(56,5): error TS2582: Cannot find name …
│ test/unit/misskey/api_client.spec.ts(57,7): error TS2582: Cannot find name …
│ test/unit/misskey/api_client.spec.ts(97,11): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(102,3): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(103,5): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(164,7): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(179,3): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(180,5): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(181,7): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(203,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(204,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(206,7): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(228,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(229,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(232,5): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(233,7): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(259,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(268,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(282,5): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(283,7): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(317,9): error TS2304: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(334,7): error TS2582: Cannot find name…
│ test/unit/misskey/api_client.spec.ts(358,9): error TS2304: Cannot find name…
│ test/unit/parser.spec.ts(81,1): error TS2582: Cannot find name 'describe'. …
│ test/unit/parser.spec.ts(84,3): error TS2304: Cannot find name 'beforeEach'.
│ test/unit/parser.spec.ts(88,3): error TS2582: Cannot find name 'describe'. …
│ test/unit/parser.spec.ts(89,5): error TS2582: Cannot find name 'describe'. …
│ test/unit/parser.spec.ts(91,7): error TS2582: Cannot find name 'it'. Do you…
│ test/unit/parser.spec.ts(92,21): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(95,9): error TS2304: Cannot find name 'expect'.
│ test/unit/parser.spec.ts(99,5): error TS2582: Cannot find name 'describe'. …
│ test/unit/parser.spec.ts(100,7): error TS2582: Cannot find name 'describe'.…
│ test/unit/parser.spec.ts(102,9): error TS2582: Cannot find name 'it'. Do yo…
│ test/unit/parser.spec.ts(103,23): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(106,11): error TS2304: Cannot find name 'expect'.
│ test/unit/parser.spec.ts(110,7): error TS2582: Cannot find name 'describe'.…
│ test/unit/parser.spec.ts(112,9): error TS2582: Cannot find name 'it'. Do yo…
│ test/unit/parser.spec.ts(113,25): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(114,27): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(118,11): error TS2304: Cannot find name 'expect'.
│ test/unit/parser.spec.ts(119,11): error TS2304: Cannot find name 'expect'.
│ test/unit/parser.spec.ts(124,5): error TS2582: Cannot find name 'describe'.…
│ test/unit/parser.spec.ts(125,7): error TS2582: Cannot find name 'describe'.…
│ test/unit/parser.spec.ts(127,9): error TS2582: Cannot find name 'it'. Do yo…
│ test/unit/parser.spec.ts(128,23): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(131,11): error TS2304: Cannot find name 'expect'.
│ test/unit/parser.spec.ts(135,7): error TS2582: Cannot find name 'describe'.…
│ test/unit/parser.spec.ts(137,9): error TS2582: Cannot find name 'it'. Do yo…
│ test/unit/parser.spec.ts(138,23): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(141,11): error TS2304: Cannot find name 'expect'.
│ test/unit/parser.spec.ts(145,7): error TS2582: Cannot find name 'describe'.…
│ test/unit/parser.spec.ts(147,9): error TS2582: Cannot find name 'it'. Do yo…
│ test/unit/parser.spec.ts(148,23): error TS2304: Cannot find name 'jest'.
│ test/unit/parser.spec.ts(151,11): error TS2304: Cannot find name 'expect'.
│ test/unit/pleroma/api_client.spec.ts(39,1): error TS2582: Cannot find name …
│ test/unit/pleroma/api_client.spec.ts(40,3): error TS2582: Cannot find name …
│ test/unit/pleroma/api_client.spec.ts(41,5): error TS2582: Cannot find name …
│ test/unit/pleroma/api_client.spec.ts(42,7): error TS2582: Cannot find name …
│ test/unit/pleroma/api_client.spec.ts(82,11): error TS2304: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(86,5): error TS2582: Cannot find name …
│ test/unit/pleroma/api_client.spec.ts(87,7): error TS2582: Cannot find name …
│ test/unit/pleroma/api_client.spec.ts(127,11): error TS2304: Cannot find nam…
│ test/unit/pleroma/api_client.spec.ts(133,3): error TS2582: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(134,5): error TS2582: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(135,7): error TS2582: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(177,9): error TS2304: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(178,9): error TS2304: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(182,5): error TS2582: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(183,7): error TS2582: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(221,9): error TS2304: Cannot find name…
│ test/unit/pleroma/api_client.spec.ts(222,9): error TS2304: Cannot find name…
│ test/unit/webo_socket.spec.ts(80,1): error TS2582: Cannot find name 'descri…
│ test/unit/webo_socket.spec.ts(83,3): error TS2304: Cannot find name 'before…
│ test/unit/webo_socket.spec.ts(87,3): error TS2582: Cannot find name 'descri…
│ test/unit/webo_socket.spec.ts(88,5): error TS2582: Cannot find name 'descri…
│ test/unit/webo_socket.spec.ts(89,7): error TS2582: Cannot find name 'descri…
│ test/unit/webo_socket.spec.ts(92,9): error TS2582: Cannot find name 'it'. D…
│ test/unit/webo_socket.spec.ts(93,23): error TS2304: Cannot find name 'jest'.
│ test/unit/webo_socket.spec.ts(96,11): error TS2304: Cannot find name 'expec…
│ test/unit/webo_socket.spec.ts(99,7): error TS2582: Cannot find name 'descri…
│ test/unit/webo_socket.spec.ts(102,9): error TS2582: Cannot find name 'it'. …
│ test/unit/webo_socket.spec.ts(103,23): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(106,11): error TS2304: Cannot find name 'expe…
│ test/unit/webo_socket.spec.ts(111,5): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(112,7): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(118,9): error TS2582: Cannot find name 'it'. …
│ test/unit/webo_socket.spec.ts(119,23): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(122,11): error TS2304: Cannot find name 'expe…
│ test/unit/webo_socket.spec.ts(125,7): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(131,9): error TS2582: Cannot find name 'it'. …
│ test/unit/webo_socket.spec.ts(132,25): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(133,27): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(137,11): error TS2304: Cannot find name 'expe…
│ test/unit/webo_socket.spec.ts(138,11): error TS2304: Cannot find name 'expe…
│ test/unit/webo_socket.spec.ts(143,5): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(144,7): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(149,9): error TS2582: Cannot find name 'it'. …
│ test/unit/webo_socket.spec.ts(150,23): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(153,11): error TS2304: Cannot find name 'expe…
│ test/unit/webo_socket.spec.ts(157,7): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(162,9): error TS2582: Cannot find name 'it'. …
│ test/unit/webo_socket.spec.ts(163,23): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(166,11): error TS2304: Cannot find name 'expe…
│ test/unit/webo_socket.spec.ts(170,7): error TS2582: Cannot find name 'descr…
│ test/unit/webo_socket.spec.ts(175,9): error TS2582: Cannot find name 'it'. …
│ test/unit/webo_socket.spec.ts(176,23): error TS2304: Cannot find name 'jest…
│ test/unit/webo_socket.spec.ts(179,11): error TS2304: Cannot find name 'expe…
└─ Failed in 6.3s at /home/sharkey/sharkey/packages/megalodon
packages/misskey-js build$ tsc
└─ Done in 2.6s
/home/sharkey/sharkey/packages/megalodon:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  megalodon@7.0.1 build: `tsc -p ./`
Exit status 2
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Mar0xy** [comment]
I have updated the install script

**Comment by alcapurrias** [comment]
That worked, thanks so much 🙂
