### ISSUE TITLE
When hovering over a user's avatar, popup window should indicate if the user has follow-requests on

### ISSUE THREAD

**Issue by 1bcb** [transfem-org/Sharkey#49]
## Summary

This is a request to port [a feature from Firefish](https://git.joinfirefish.org/firefish/firefish/-/issues/10368).  

### What I Want
Currently, if you view the profile of another user, and following that user requires their approval, a small lock icon is displayed next to their username.  

On the other hand, if you are viewing a thread, and you hover your mouse over a user's avatar, the summarized version of their profile does not display this lock icon.  As far as I can tell, it gives no indication as to whether the user in question requires followers to be manually approved.  

I believe this interface should be changed so that the pop-up shows some indication that the user approves follow requests.

### Why this feature would be useful

You can follow a user (or submit a follow-request) directly from the pop-up window without needing to load their full profile.  But if a user requires follow-requests, then it's probably a better idea to go to their full profile and read their pinned posts before sending a request.  I think it would be helpful to know right away which users are open to quick follows.
My particular use case is that when I read threads, I tend to want to quickly follow every user who makes a reply I like, as long as they are open to new followers.  I really like the pop-up profiles on Sharkey because it makes doing this much faster: when I used Mastodon, I had to load every user's profile in a new tab to check if I already followed them and to start following them if I didn't.
If I try to follow a user who approves followers, then I don't find out until after I have sent the follow request and see an hour-glass symbol.  That leaves me with two options:
1)Stop reading the thread, go to the user's profile, read carefully to make sure that I am the kind of person they are okay getting a follow-request from, and then (preferably) send them a DM saying why I am following.  If I'm the kind of person they don't want to follow them for some reason, then I should revoke my follow request.
2)Immediately withdraw my follow-request and continue reading the thread.  I'm not sure if sending a follow-request and immediately withdrawing it gives them a notification: if it does then I'd rather avoid this step.
This process would go much faster if I could see who locks their followers directly from the pop-up window.

**Comment by Mar0xy** [comment]
I hope this satisfies you :)

Followed:

![image](https://github.com/transfem-org/Sharkey/assets/8841466/c8bae579-77d9-4ec7-92eb-ac60277d59bc)

If someone following you has their account locked and you don't follow them:

![image](https://github.com/transfem-org/Sharkey/assets/8841466/fff959f6-ec8e-4f2e-a5e0-87b5a2daa9e4)

Not Followed and Not Following:

![image](https://github.com/transfem-org/Sharkey/assets/8841466/52ea7f0f-3757-427b-9a81-fe67bf819311)
