### ISSUE TITLE
Mark the presence of a poll when showing a non-detailed note

### ISSUE THREAD

**Issue by dakkar** [transfem-org/Sharkey#52]
When showing a note up-thread, that has an image or video, the little "▶️(1 files(s))" is shown:
![image](https://github.com/transfem-org/Sharkey/assets/86328/a9dda7b3-a3e7-4d18-83b0-e83a05d2148c)

When the note has a poll, nothing is shown:
![image](https://github.com/transfem-org/Sharkey/assets/86328/ba11d0e6-52e4-4afa-8d59-1b2c2f4bdbe2)
(and yes, that note has a poll:
![image](https://github.com/transfem-org/Sharkey/assets/86328/a3e40049-f881-47a1-8a44-b80ea448c2f7)
)

It would be helpful to have something like "▶️(poll)" that can be expanded to show the poll

**Comment by dakkar** [comment]
doesn't seem to have been enough:
![image](https://github.com/transfem-org/Sharkey/assets/86328/0660bd4c-d981-4aac-9f56-2781d4f8fc5b)
![image](https://github.com/transfem-org/Sharkey/assets/86328/fea235ee-6e87-403e-afc7-25aba70fa940)

maybe the frontend needs to know as well?

**Comment by dakkar** [comment]
that's bizarre

**Comment by dakkar** [comment]
aha! when showing a note with only 1 "parent", the frontend calls `/notes/chidren`, which ends with https://github.com/transfem-org/Sharkey/blob/develop/packages/backend/src/server/api/endpoints/notes/children.ts#L77
```
return await this.noteEntityService.packMany(notes, me);
```
and probably needs the same change as https://github.com/transfem-org/Sharkey/commit/f81d6f8e24aabe3a4a985c1b0e5bf5eded26d9e4

also, when showing a timeline https://github.com/transfem-org/Sharkey/blob/develop/packages/backend/src/server/api/endpoints/notes/timeline.ts#L148

I think it would be simpler (and result in better performance overally) if we changed https://github.com/transfem-org/Sharkey/blob/develop/packages/backend/src/core/entities/NoteEntityService.ts#L363 to always include poll details, regardless of `opts.detail`

**Comment by Mar0xy** [comment]
> always include poll details, regardless of opts.detail

While this seems simpler it would actually not result in better performance as it would then always need to call additional data through the DB

But thanks for the hint towards the other two endpoints

**Comment by dakkar** [comment]
maybe also `global-timeline`, `local-timeline`, `hybrid-timeline`, `renotes`, `replies`, `search`… is there ever a case in which we don't want to expose that there's a poll?

would it be sensible (with an eye to future maintability, and minimising merge conflicts from upstream) to only expose that there is a poll (a boolean), and let the frontend lazy-load the poll details via a new endpoint?

(I may be over-thinking and over-complicating this…)

**Comment by Mar0xy** [comment]
I have just checked the poll section in `NoteEntityService` and it should be possible to just move poll out of the detail boolean.
