### ISSUE TITLE
Edits do not properly federate

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#53]
## 💡 Summary
Edits SK->FF work perfectly fine, but it seems that most of the other instance types reject the edits.

Sharkey's editing system misses the mark a bit.
https://fedi.cpluspatch.com/notice/AaQrPdpsYoJnVNOaem - Sharkey to Akkoma :x: 
https://kitsunes.club/notes/9kfjfrdoxujlb38i - Sharkey to Firefish :heavy_check_mark: 
https://tech.lgbt/@kio@kitsunes.gay/111177732228061879 - Sharkey to Mastodon :x:

Firefish's editing system seems to work perfectly fine. 
https://fedi.cpluspatch.com/notice/AaQqpKPpHqyQqitV20 - Firefish to Akkoma :heavy_check_mark: 
https://kitsunes.gay/notes/9kfj7augrx - Firefish to SK :heavy_check_mark: 
https://tech.lgbt/@Kio@kitsunes.club/111177706403113308 - Firefish to Mastodon :heavy_check_mark: 

## 🥰 Expected Behavior
Edits propogate to most/all instances.

## 🤬 Actual Behavior
Edits are discarded by most other software types.

## 📝 Steps to Reproduce

1. Make a post
2. Edit a post
3. Veiw yruo msaterpeece on another instance

### 💻 Frontend
* Model and OS of the device(s):
Custom Built PC on Ubuntu.
  
* Browser:
Firefox 117.0.1 Snap
  
* Server URL:
Kitsunes.gay
  
* Misskey:
2023.9.1.beta3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Docker Stack w/ Swarm
* Misskey: 2023.9.1.beta3

**Comment by Mar0xy** [comment]
Should be fixed with the latest 2 commits the issue was that there was no `updated` field included in the edited note object when send out which caused every other software to not pick it up.
