### ISSUE TITLE
Custom font on the administrator frontend

### ISSUE THREAD

**Issue by garfieldairlines** [transfem-org/Sharkey#64]
## Summary

Just as I said on discord yesterday evening, I had the idea of being able to add custom font files directly in the admin interface, just like the custom icons and so on in the branding menu.

Ideally ttf, woff and woff2.

**Comment by Mar0xy** [comment]
So now tell me how would you load custom font files into a SCSS file?

**Comment by Mar0xy** [comment]
The custom Icon/Images in the branding menu are all just URLs that replace the defaults on the loading screen and in the meta tags which got nothing to do with the actual css files.

In general terms modifying a SCSS file via DB would be technically impossible so if someone wants a custom font they need to just modify it manually.

**Comment by Mar0xy** [comment]
Don't worry if I came over aggressive it just sometimes happen cause I tend to be very direct when it comes to technical stuff.
