### ISSUE TITLE
Bring back refresh profile information

### ISSUE THREAD

**Issue by codingneko** [transfem-org/Sharkey#70]
## Summary

Bring back the functionality to manually update a remote user's profile.
There used to be a button in what used to be user information (now renamed to "Moderation"), for updating remote user information. It was very handy, and it was removed for some reason... Firefish still has it:
![image](https://github.com/transfem-org/Sharkey/assets/11065075/146c25d1-10f7-4520-acf3-058c56fbc7e3)

Could we bring that back?

**Comment by Mar0xy** [comment]
Fixed in https://github.com/transfem-org/Sharkey/commit/005d7b6da50033c11d7daa589df4655999854345
