### ISSUE TITLE
Fix click to open post related issues

### ISSUE THREAD

**Issue by Mar0xy** [transfem-org/Sharkey#71]
Click to open tends to cause a lot of issues like opening up a post when showing a CW note, causing the router to freak out and etc these should all be fixed relatively quickly.

Video of router glitching out:

https://github.com/transfem-org/Sharkey/assets/8841466/549d10e6-492f-4a3e-a891-65a4062e6daa

**Comment by Kio-td** [comment]
One of my users suggested we have a toggle to disable click to open unkess you click/tap the post date.

**Comment by Mar0xy** [comment]
> One of my users suggested we have a toggle to disable click to open unkess you click/tap the post date.

Is already on the Project boards todo list

**Comment by Mar0xy** [comment]
Fixed in https://github.com/transfem-org/Sharkey/commit/731a686b571170c82ba416adda0a6acc6154e2fb
