### ISSUE TITLE
bug: Reports are not emailed

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#81]
## 💡 Summary
It appears that when I have changed my email. I have lost the ability to receive emails about reports that were made on or against the server.

## 🥰 Expected Behavior
When a report is created, Sharkey will send an email to the administrators, regardless if it's been changed or not.

## 🤬 Actual Behavior
Nothing.

## 📝 Steps to Reproduce

1. Change your email
2. Make a report.
3.

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service:  Docker-Compose
* Misskey: 2023.10.1
* Node: Unknown.
* PostgreSQL: postgresql:15
* Redis: redis:latest

**Comment by Mar0xy** [comment]
This has already not worked since 2023.9.1 even with an email that hasn't been changed I assume it was either ripped out or it broke

**Comment by Kio-td** [comment]
It was working until just now, actually, when me and my administrator changed our emails, eheh.
