### ISSUE TITLE
Page jumps to top when new posts are loaded in the profile page

### ISSUE THREAD

**Issue by Freeplayg** [transfem-org/Sharkey#82]
## 💡 Summary

When you scroll down to load more posts in someone's profile, the page seems to jump around a lot, and mainly goes back to the top of the page

## 🥰 Expected Behavior

The page should not jump around

## 🤬 Actual Behavior

[Screencast from 2023-10-16 17-23-24.webm](https://github.com/transfem-org/Sharkey/assets/40742947/a851793b-5d68-479f-a1f7-66a325e817f2)

## 📌 Environment

Any profile page, v.2023.10.1

### 💻 Frontend
* Model and OS of the device(s): Fedora 38 w/ Gnome
* Browser: Firefox
* Server URL: kitsunes.club
* Misskey: 2023.10.1

**Comment by Insert5StarName** [comment]
im looking into this, could take a bit till its fixed.

**Comment by Insert5StarName** [comment]
found a fix, should be working as expected next release

**Comment by Insert5StarName** [comment]
confirmed to be fixed in https://github.com/transfem-org/Sharkey/commit/4d71afa8841223a150c00d0828906ff990c13c11
