### ISSUE TITLE
bug: unable to see what I'm typing when replying/quoteboosting

### ISSUE THREAD

**Issue by MoshiBar** [transfem-org/Sharkey#99]
## 💡 Summary

In mobile UI, when replying to a tall post or quote boosting it, the text box becomes obscured by the keyboard and can't be scrolled up to be visible

## 🥰 Expected Behavior

be able to scroll down, or some other behavior that makes it visible

## 🤬 Actual Behavior

text box is obscured so I can't see what I'm typing, or the preview
![Screenshot_20231018-093257](https://github.com/transfem-org/Sharkey/assets/25570708/535c65df-0108-4743-a1e9-7f6202b3c9ae)

## 📝 Steps to Reproduce

1. open the reply dialog or quote boost dialog, and try to type in it

### 💻 Frontend
* Model and OS of the device(s):
  Google Pixel 6; GrapheneOS
* Browser:
  Firefox Mobile
* Server URL:
  ambrosia.moe
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: baremetal/systemd
* Sharkey: commit f71a675
* Node: 19.9.0
* PostgreSQL: unknown
* Redis: unknown
* OS and Architecture: Debian 11 x86-64

**Comment by Insert5StarName** [comment]
u can colapse the file, tho i agree that this should be fixed

**Comment by MoshiBar** [comment]
> u can colapse the file, tho i agree that this should be fixed

yeah I noticed that after posting, but it's not really intuitive and the button is hard to get on mobile

**Comment by Insert5StarName** [comment]
yeah needs to be improved
